// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CLQCodeGen.CodeTemplates.SubTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class SetupAspectLoaderMock : BaseSubTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 5 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"

    foreach (var methodInfo in GetAllMethods())
    {
        if (GetIsReturnGenericList(methodInfo) && GetIsSingleReferenceParameter(methodInfo))
        {
            var parameterType0 = GetParameterGenericType(methodInfo, 0);
            var returnType = GetReturnListGenericType(methodInfo);
            var returnListName = $"{GetVariableNameFromType(returnType)}List";

            
            #line default
            #line hidden
            this.Write("\r\n            var ");
            
            #line 15 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnListName));
            
            #line default
            #line hidden
            this.Write(" = new List<");
            
            #line 15 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnType.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n            {\r\n                // new EmployeeAspect(),\r\n                // ne" +
                    "w EmployeeAspect()\r\n            };\r\n\r\n            ");
            
            #line 21 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMockVariableName()));
            
            #line default
            #line hidden
            this.Write("\r\n                .Setup(g => g.");
            
            #line 22 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetMethodName(methodInfo)));
            
            #line default
            #line hidden
            this.Write("(It.IsAny<IList<");
            
            #line 22 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterType0.Name));
            
            #line default
            #line hidden
            this.Write(">>()))\r\n                .Returns<IList<");
            
            #line 23 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameterType0.Name));
            
            #line default
            #line hidden
            this.Write(">>(\r\n                    rs => ");
            
            #line 24 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(returnListName));
            
            #line default
            #line hidden
            this.Write(".Where(a => rs.Any(r => r.Equals(a.Reference))).ToList());\r\n");
            
            #line 25 "C:\Users\s1ig\Documents\Visual Studio 2015\Projects\CLQCodeGen\CLQCodeGen\CodeTemplates\SubTemplates\SetupAspectLoaderMock.tt"

        }
    }

            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
