//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace DBQuerier.DataObj {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("QueryDefination", Namespace="http://tempuri.org/QueryDef.xsd", IsNullable=false)]
    public partial class QueryDefType {
        
        private string qureyNameField;
        
        private string queryStringField;
        
        private QueryParmDef[] parameterField;
        
        private ExtraColumnDef[] extraColumnField;
        
        private ContextMenuDef contextMenuField;
        
        /// <remarks/>
        public string QureyName {
            get {
                return this.qureyNameField;
            }
            set {
                this.qureyNameField = value;
            }
        }
        
        /// <remarks/>
        public string QueryString {
            get {
                return this.queryStringField;
            }
            set {
                this.queryStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Parameter")]
        public QueryParmDef[] Parameter {
            get {
                return this.parameterField;
            }
            set {
                this.parameterField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ExtraColumn")]
        public ExtraColumnDef[] ExtraColumn {
            get {
                return this.extraColumnField;
            }
            set {
                this.extraColumnField = value;
            }
        }
        
        /// <remarks/>
        public ContextMenuDef ContextMenu {
            get {
                return this.contextMenuField;
            }
            set {
                this.contextMenuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class QueryParmDef {
        
        private string nameField;
        
        private QueryParmType parameterTypeField;
        
        private string tableFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public QueryParmType ParameterType {
            get {
                return this.parameterTypeField;
            }
            set {
                this.parameterTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TableField {
            get {
                return this.tableFieldField;
            }
            set {
                this.tableFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public enum QueryParmType {
        
        /// <remarks/>
        String,
        
        /// <remarks/>
        TrimStr,
        
        /// <remarks/>
        Integer,
        
        /// <remarks/>
        Int64,
        
        /// <remarks/>
        Guid,
        
        /// <remarks/>
        DateTime,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenuItemXmlSaverDef))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MenuItemXmlViewerDef))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class ContextMenuItemDef {
        
        private string[] sourceColumnField;
        
        private string itemNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("SourceColumn")]
        public string[] SourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ItemName {
            get {
                return this.itemNameField;
            }
            set {
                this.itemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class MenuItemXmlSaverDef : ContextMenuItemDef {
        
        private string saveDirectoryField;
        
        /// <remarks/>
        public string SaveDirectory {
            get {
                return this.saveDirectoryField;
            }
            set {
                this.saveDirectoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class MenuItemXmlViewerDef : ContextMenuItemDef {
        
        private string viewAppField;
        
        /// <remarks/>
        public string ViewApp {
            get {
                return this.viewAppField;
            }
            set {
                this.viewAppField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class ContextMenuDef {
        
        private ContextMenuItemDef[] itemsField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("MenuItemXmlSaver", typeof(MenuItemXmlSaverDef))]
        [System.Xml.Serialization.XmlElementAttribute("MenuItemXmlViewer", typeof(MenuItemXmlViewerDef))]
        public ContextMenuItemDef[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/QueryDef.xsd")]
    public partial class ExtraColumnDef {
        
        private string xPathField;
        
        private string sourceColumnField;
        
        private string columnNameField;
        
        /// <remarks/>
        public string xPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceColumn {
            get {
                return this.sourceColumnField;
            }
            set {
                this.sourceColumnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ColumnName {
            get {
                return this.columnNameField;
            }
            set {
                this.columnNameField = value;
            }
        }
    }
}
