// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 14.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CLQCodeGen.CodeTemplates
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CLQCodeGen.CodeTemplates.SubTemplates;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "14.0.0.0")]
    public partial class StaticModelType : BaseMainTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 7 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    WriteSubTemplate(typeof(SubTemplates.CopyRight.CopyRight), GetModelTypeName());

            
            #line default
            #line hidden
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Diagnostics.CodeAn" +
                    "alysis;\r\nusing System.Diagnostics.Contracts;\r\nusing System.IO;\r\nusing System.Lin" +
                    "q;\r\n\r\nnamespace ");
            
            #line 17 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeNamespace()));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n    /// <summary>\r\n    /// The ");
            
            #line 20 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(" ", GetModelTypeNameWords())));
            
            #line default
            #line hidden
            this.Write(".\r\n    /// </summary>\r\n    [ExcludeFromCodeCoverage]\r\n    [Serializable]\r\n    pub" +
                    "lic struct ");
            
            #line 24 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\r\n    {\r\n        #region static\r\n        \r\n");
            
            #line 28 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

        var codePairList = GetCodeNamePairs();

            
            #line default
            #line hidden
            this.Write("        /// <summary>\r\n        /// Defines the possible code values.\r\n        ///" +
                    " </summary>\r\n        public static class Codes\r\n        {\r\n");
            
            #line 36 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    for (int i = 0; i < codePairList.Count; ++i)
    {
        var codePair = codePairList[i];
    
        if (i > 0) WriteLine("");

            
            #line default
            #line hidden
            this.Write("            /// <summary>\r\n            /// The ");
            
            #line 44 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.Code.ToLower()));
            
            #line default
            #line hidden
            this.Write(" type.\r\n            /// </summary>\r\n            public const string ");
            
            #line 46 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.CodeVar));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 46 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.CodeValue));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 47 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        /// <summary>\r\n        /// Defines the possible name values." +
                    "\r\n        /// </summary>\r\n        internal static class Names\r\n        {\r\n");
            
            #line 57 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    for (int i = 0; i < codePairList.Count; ++i)
    {
        var codePair = codePairList[i];
    
        if (i > 0) WriteLine("");

            
            #line default
            #line hidden
            this.Write("            public const string ");
            
            #line 64 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.NameVar));
            
            #line default
            #line hidden
            this.Write(" = \"");
            
            #line 64 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.NameValue));
            
            #line default
            #line hidden
            this.Write("\";\r\n");
            
            #line 65 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    }

            
            #line default
            #line hidden
            this.Write("        }\r\n\r\n        static ");
            
            #line 70 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("()\r\n        {\r\n            Empty = new ");
            
            #line 72 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("(string.Empty, string.Empty);\r\n");
            
            #line 73 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    foreach (var codePair in codePairList)
    {

            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 77 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.ClassVar));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 77 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("(Codes.");
            
            #line 77 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.CodeVar));
            
            #line default
            #line hidden
            this.Write(", Names.");
            
            #line 77 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.NameVar));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 78 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n            All = new[]\r\n            {\r\n");
            
            #line 84 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    for (int i = 0; i < codePairList.Count; ++i)
    {
        var codePair = codePairList[i];
        var isLast = (i+1 == codePairList.Count);

            
            #line default
            #line hidden
            this.Write("                ");
            
            #line 90 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.Code));
            
            #line default
            #line hidden
            
            #line 90 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(isLast ? "" : ","));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 91 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    }

            
            #line default
            #line hidden
            this.Write("            };\r\n        }\r\n\r\n        /// <summary>\r\n        /// Defines the empty" +
                    " ");
            
            #line 98 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </summary>\r\n        public static readonly ");
            
            #line 100 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" Empty;\r\n\r\n        #region Define the several possible values\r\n\r\n        /// <sum" +
                    "mary>\r\n        /// Defines list of all possible QuotationDocumentReportingModelT" +
                    "ype.\r\n        /// </summary>\r\n        public static readonly IEnumerable<");
            
            #line 107 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("> All;\r\n");
            
            #line 108 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    for (int i = 0; i < codePairList.Count; ++i)
    {
        var codePair = codePairList[i];

            
            #line default
            #line hidden
            this.Write("\r\n        private static readonly ");
            
            #line 114 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 114 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.ClassVar));
            
            #line default
            #line hidden
            this.Write(";\r\n\r\n        /// <summary>\r\n        /// Gets the ");
            
            #line 117 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.Code.ToLower()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 117 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </summary>\r\n        /// <value>\r\n        /// The ");
            
            #line 120 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.Code.ToLower()));
            
            #line default
            #line hidden
            this.Write(" type value.\r\n        /// </value>\r\n        public static ");
            
            #line 122 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 122 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.Code));
            
            #line default
            #line hidden
            this.Write("\r\n        {\r\n            get { return ");
            
            #line 124 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(codePair.ClassVar));
            
            #line default
            #line hidden
            this.Write("; }\r\n        }\r\n");
            
            #line 126 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"

    }

            
            #line default
            #line hidden
            this.Write("\r\n        #endregion\r\n\r\n        #endregion\r\n\r\n        private readonly string _co" +
                    "de;\r\n        private readonly string _name;\r\n\r\n        internal ");
            
            #line 137 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(@"(string code, string name)
        {
            Contract.Requires<ArgumentNullException>(code != null, ""code"");
            Contract.Requires<ArgumentNullException>(name != null, ""name"");

            _code = code;
            _name = name;
        }

        #region properties

        /// <summary>
        /// Gets the code.
        /// </summary>
        /// <value>
        /// The code of ");
            
            #line 152 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </value>\r\n        public string Code\r\n        {\r\n            get {" +
                    " return _code; }\r\n        }\r\n\r\n        /// <summary>\r\n        /// Gets the name." +
                    "\r\n        /// </summary>\r\n        /// <value>\r\n        /// The name of ");
            
            #line 163 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </value>\r\n        public string Name\r\n        {\r\n            get {" +
                    " return _name; }\r\n        }\r\n\r\n        #endregion\r\n\r\n        #region Caster and " +
                    "IEquatable stuff\r\n\r\n        /// <summary>\r\n        /// Catches an instance of <s" +
                    "ee cref=\"");
            
            #line 175 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see> given a code.\r\n        /// </summary>\r\n        /// <param name=\"code\">Th" +
                    "e code of <see cref=\"");
            
            #line 177 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</param>\r\n        /// <returns>An instance of <see cref=\"");
            
            #line 178 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</returns>\r\n        public static implicit operator ");
            
            #line 179 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(@"(string code)
        {
            try
            {
                return string.IsNullOrEmpty(code)
                    ? Empty
                    : All.First(type => string.Equals(type.Code, code, StringComparison.OrdinalIgnoreCase));
            }
            catch (InvalidOperationException exception)
            {
                throw new InvalidDataException(
                    string.Format(
                        """);
            
            #line 191 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(@" Code [{0}] is an invalid value. Available codes: [{1}]"", 
                        code,
                        string.Join("", "", All.Select(t => t.Code))),
                    exception);
            }
        }

        /// <summary>
        /// The op_ explicit.
        /// </summary>
        /// <param name=""type"">
        /// The ");
            
            #line 202 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".\r\n        /// </param>\r\n        /// <returns>The code of given ");
            
            #line 204 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(".</returns>\r\n        public static explicit operator string(");
            
            #line 205 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" type)\r\n        {\r\n            return type.Code;\r\n        }\r\n\r\n        /// <summa" +
                    "ry>\r\n        /// Operator overload for ==.\r\n        /// </summary>\r\n        /// " +
                    "<param name=\"left\">The left <see cref=\"");
            
            #line 213 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</param>\r\n        /// <param name=\"right\">The right <see cref=\"");
            
            #line 214 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</param>\r\n        /// <returns>\r\n        ///   <c>true</c> if two <see c" +
                    "ref=\"");
            
            #line 216 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see> instances are equal. Otherwise <c>false</c>.\r\n        /// </returns>\r\n  " +
                    "      public static bool operator ==(");
            
            #line 218 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" left, ");
            
            #line 218 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" right)\r\n        {\r\n            return left.Equals(right);\r\n        }\r\n\r\n        " +
                    "/// <summary>\r\n        /// Operator overload for !=.\r\n        /// </summary>\r\n  " +
                    "      /// <param name=\"left\">The left <see cref=\"");
            
            #line 226 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</param>\r\n        /// <param name=\"right\">The right <see cref=\"");
            
            #line 227 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see>.</param>\r\n        /// <returns>\r\n        ///   <c>true</c> if two <see c" +
                    "ref=\"");
            
            #line 229 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write("\"></see> instances are not equal. Otherwise <c>false</c>.\r\n        /// </returns>" +
                    "\r\n        public static bool operator !=(");
            
            #line 231 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(" left, ");
            
            #line 231 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(@" right)
        {
            return !(left == right);
        }

        /// <summary>
        /// Determines whether the specified <see cref=""System.Object"" />, is equal to this instance.
        /// </summary>
        /// <param name=""obj"">The <see cref=""System.Object"" /> to compare with this instance.</param>
        /// <returns>
        ///   <c>true</c> if the specified <see cref=""System.Object"" /> is equal to this instance; otherwise, <c>false</c>.
        /// </returns>
        public override bool Equals(object obj)
        {
            if (obj is ");
            
            #line 245 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(")\r\n            {\r\n                var right = (");
            
            #line 247 "C:\Users\s1ig\Documents\GitHub\MockMFC_CodePlex\ConsoleApp\CLQCodeGen\CLQCodeGen\CodeTemplates\StaticModelType.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetModelTypeName()));
            
            #line default
            #line hidden
            this.Write(@")obj;
                return Code == right.Code;
            }

            return false;
        }

        /// <summary>
        /// Returns a hash code for this instance.
        /// </summary>
        /// <returns>
        /// A hash code for this instance, suitable for use in hashing algorithms and data structures like a hash table. 
        /// </returns>
        [ExcludeFromCodeCoverage]
        public override int GetHashCode()
        {
            return Code.GetHashCode();
        }

        /// <summary>
        /// The to string.
        /// </summary>
        /// <returns>
        /// The <see cref=""string""/>.
        /// </returns>
        public override string ToString()
        {
            return Code;
        }

        #endregion
    }
}");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
}
